[workspace]
members = [
]

[package]
name = "soem"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

# [lib]
# name = "c2rust"
# path = "lib.rs"
# crate-type = ["staticlib", "rlib"]


[dependencies]
c2rust-bitfields = "0.3"
libc = "0.2"
